### ISSUE TITLE
porder order says invalid geometry but geojsonlinter says is valid

### ISSUE THREAD

**Issue by rbavery** [samapriya/porder#11]
I'm trying the following, 

```
(porder-env) (v2-cloud)~/cloud-free-planet/notebooks$ porder order --name test_tile_eighth_May-September --idlist ~/cloud-free-planet/notebooks/test_tile_eighth.txt --item PSScene4Band --asset analytic_sr --boundary test_tile_eighth_fixed.geojson --op clip
```
the order fails without returning a url and with the following error

```
Could not parse geometry
{"field":null,"general":[{"message":"Unable to accept order: geojson: invalid geometry"}]}
```
But I've checked that my geojson is valid with http://geojsonlint.com/ and no errors from the spec are reported. Any help is appreciated!

My geojson is 

```
{
  "type": "FeatureCollection",
  "name": "test_tile_eighth",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": 0
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -0.831053947078279,
              5.72196597574407
            ],
            [
              -0.831,
              5.71
            ],
            [
              -0.815323594266615,
              5.709838158765161
            ],
            [
              -0.815377541344895,
              5.721804134509231
            ],
            [
              -0.831053947078279,
              5.72196597574407
            ]
          ]
        ]
      }
    }
  ]
}
```
and my id file is attached

[test_tile_eighth.txt](https://github.com/samapriya/porder/files/2892878/test_tile_eighth.txt)

I can order without clipping just fine, for now it is clipping to the boundary that causes the order to fail.

**Comment by samapriya** [comment]
@rbavery it might be an intermittent issue because I was able to run it using your idlist and geojson you provided. I would suggest you retry using the same tool

```
porder order --name "rtest" --idlist "C:\Users\samapriya\Downloads\test_tile_eighth.txt" --item "PSScene4Band" --asset "analytic" --boundary "C:\Users\samapriya\Downloads\ryan.geojson" --op clip
Order created at https://api.planet.com/compute/ops/orders/v2/01fb6868-12b8-467b-9c58-c76905aed67b and url copied to clipboard
```

**Comment by rbavery** [comment]
I've tried that function call multiple times over the past few days and I keep getting the same error, so I think something else is going on. I found the portion of the code in order_now.py that is failing, this try block

```
    for key,value in kwargs.items():
        if key=='boundary' and value!=None:
                for items in k['tools']:
                    if items.get('clip'):
                        try:
                            if value.endswith('.geojson'):
                                with open(value) as aoi:
                                    aoi_resp = json.load(aoi)
                                    items['clip']['aoi']['coordinates']= aoi_resp['features'][0]['geometry']['coordinates']
                            elif value.endswith('.json'):
                                with open (value) as aoi:
                                    aoi_resp=json.load(aoi)
                                    items['clip']['aoi']['coordinates']=aoi_resp['config'][0]['config']['coordinates']
                            elif value.endswith('.kml'):
                                getcoord=kml2coord(value)
                                items['clip']['aoi']['coordinates']=getcoord
                        except Exception as e:
                            print('Could not parse geometry')
```
So I tried to replicate the try block in my porder env... and I can read in the geojson just fine.
```
>>> import json
>>> json.load(open("test_tile_eighth.geojson"))
{u'type': u'FeatureCollection', u'name': u'test_tile_eighth', u'features': [{u'geometry': {u'type': u'Polygon', u'coordinates': [[[-0.831053947078279, 5.72196597574407], [-0.831, 5.71], [-0.815323594266615, 5.709838158765161], [-0.815377541344895, 5.721804134509231], [-0.831053947078279, 5.72196597574407]]]}, u'type': u'Feature', u'properties': {u'id': 0}}]}
>>> aoi_resp = json.load(open("test_tile_eighth.geojson"))
>>> aoi_resp['features']
[{u'geometry': {u'type': u'Polygon', u'coordinates': [[[-0.831053947078279, 5.72196597574407], [-0.831, 5.71], [-0.815323594266615, 5.709838158765161], [-0.815377541344895, 5.721804134509231], [-0.831053947078279, 5.72196597574407]]]}, u'type': u'Feature', u'properties': {u'id': 0}}]
>>> aoi_resp['features'][0]
{u'geometry': {u'type': u'Polygon', u'coordinates': [[[-0.831053947078279, 5.72196597574407], [-0.831, 5.71], [-0.815323594266615, 5.709838158765161], [-0.815377541344895, 5.721804134509231], [-0.831053947078279, 5.72196597574407]]]}, u'type': u'Feature', u'properties': {u'id': 0}}
>>> aoi_resp['features'][0]['geometry']
{u'type': u'Polygon', u'coordinates': [[[-0.831053947078279, 5.72196597574407], [-0.831, 5.71], [-0.815323594266615, 5.709838158765161], [-0.815377541344895, 5.721804134509231], [-0.831053947078279, 5.72196597574407]]]}
>>> aoi_resp['features'][0]['geometry']['coordinates']
[[[-0.831053947078279, 5.72196597574407], [-0.831, 5.71], [-0.815323594266615, 5.709838158765161], [-0.815377541344895, 5.721804134509231], [-0.831053947078279, 5.72196597574407]]]

```
my hunch is that this is failing because the value that is associated with key `boundary` is not a string that ends with '.geojson' on my linux system, but something else. thus it would fail on `value.endswith('.geojson')`. But I'm not at all sure, that's just the only thing I can think of since my porder env can parse the geometry correctly I don't know where or how else it would fail on the try block.

I'm still digging into it trying to debug, but can't seem to get my debugger in vscode to work on the file. I keep seeing an error in the call stack that says `Source code string cannot contain null bytes` Have you seen this type of error before and any suggestions?

![selection_018](https://user-images.githubusercontent.com/22258697/53262853-91be4d00-368c-11e9-8bf9-0a08376e5d15.png)

**Comment by bosth** [comment]
Seems to be resolvable by changing the line [here](https://github.com/samapriya/porder/blob/master/porder/order_now.py#L136).

Loading from a string works: `aoi_resp = json.loads(aoi.read())`

**Comment by bosth** [comment]
Seems to be resolvable by changing the line [here](https://github.com/samapriya/porder/blob/master/porder/order_now.py#L136).

Loading from a string works: `aoi_resp = json.loads(aoi.read())`

**Comment by rbavery** [comment]
Thanks @bosth and @samapriya , changing that line fixed the issue

**Comment by rbavery** [comment]
Just a heads up this was also a problem for a colleague still, should the suggestion from @bosth be incorporated into porder?

**Comment by samapriya** [comment]
Hi @rbavery made the change suggested by @bosth  and updated it in the new version. Was traveling hence the delay in getting this fixed :)

**Comment by Ntkrell** [comment]
Note: if users still get the error after seeing `aoi_resp = json.loads(aoi.read())` has been fixed, make sure to `pip install --upgrade porder`.
