### ISSUE TITLE
invalid syntax in pySmartDL.py

### ISSUE THREAD

**Issue by nakoafarrant** [samapriya/porder#19]
I copied the porder repo to my home directory to edit the line in order_now.py to aoi_resp = json.loads(aoi.read()) to fix an error in accordance with an issue fix suggested in a previous post. I ran the following code to install the porder package from that local source

```
conda create -n porder-env python=2.7.15
source activate porder-env
pip install shapely
python setup.py install
```
and this resulted in this final line of the error message
```
File "/var/folders/z2/q82ly6v96rj1snmtzthqqk740000gn/T/easy_install-xZ4yoj/pySmartDL-1.3.1/pySmartDL/pySmartDL.py", line 626
    print(status, end='', flush=True)
                                ^
SyntaxError: invalid syntax
```
Let me know if you need more of the error message to be helpful. Thanks for any help fixing this or suggested work arounds. I'm working on a Mac with OS 10.14.3

**Comment by samapriya** [comment]
Hi @nakoafarrant 
pySmartDL is a seperate project and is not owned by me. It seems the latest version 1.3.1 removed python 2 support so you should be able to force install

```pip install pySmartDL==1.2.5```

I have tested this with Python 2 and if issues persist, feel free to open it on their [project page](https://github.com/iTaybb/pySmartDL/)
