### ISSUE TITLE
order didn't produce url, no error given

### ISSUE THREAD

**Issue by jimoreira** [samapriya/porder#20]
hi, i'm using this tool for the fist time. 
It seems that everything is working ok. 
i manage to get the `idlist` and to place an order (after a few trys) with :
`porder order --name "tabare1" --idlist "D:\OneDrive\teleysig_javierMoreira\TrabajoFinal\Tesis\VALIDACION\CHACRAS\imagenes\split\tabare_init.csv" --item "PSScene4Band" --asset "analytic_sr" --boundary "D:\OneDrive\teleysig_javierMoreira\TrabajoFinal\Tesis\VALIDACION\CHACRAS\TABARE.geojson" --op clip zip email`
my question: 
i have no response, no by mail, neither in the cmd. I have tried first a fairly large number of images (50), spliting the ` idlist`: but then, i have tried with 10 images, to check if that was the problem. 
No response in either case.
how much is a reasonable time to wait? i should be an hour ago since my last try.

thanks!

**Comment by samapriya** [comment]
Hi @jimoreira you should be able to check if your order was placed at this [endpoint](https://api.planet.com/compute/ops/orders/v2). Use your API key as the username, and you should be able to login, you can leave password empty. This page should show all your orders. Just so we are clear did you get any error message or any print out? If there are no error messages there is nothing else to diagnose without the idlist and the GeoJSON file you are using.

**Comment by jimoreira** [comment]
thanks for your reply..
no orders in that endpoint.
the only step I couldn't make work is the `base64`, but since I'm not using any cloud storage, I thought it may be ok. And also, no errors appear.

Also when I initiate planet, I used mail and password, and no problems. I tried to use 
`set PL_API_KEY=Your API Key`
but it didn't work.

Maybe, something about the geojson file:
When i run `porder idlist` in some ocassions give me this error (but still produced the .txt and .csv files):
`porder idlist --input "D:\OneDrive\teleysig_javierMoreira\TrabajoFinal\Tesis\VALIDACION\CHACRAS\TABARE.geojson" --start "2017-10-01" --end "2017-12-27" --item "PSScene4Band" --asset "analytic_sr" --number 500 --outfile "D:\OneDrive\teleysig_javierMoreira\TrabajoFinal\Tesis\VALIDACION\CHACRAS\imagenes\tabare2.csv"`

`'features'
Traceback (most recent call last):
  File "C:\Python27\Scripts\porder-script.py", line 11, in <module>
    load_entry_point('porder==0.1.9', 'console_scripts', 'porder')()
  File "c:\python27\lib\site-packages\porder\porder.py", line 213, in main
    args.func(args)
  File "c:\python27\lib\site-packages\porder\porder.py", line 71, in idlist_from_parser
    outfile=args.outfile)
  File "c:\python27\lib\site-packages\porder\geojson2id.py", line 180, in idl
    while page['_links'].get('_next') is not None:
KeyError: '_links' `

**Comment by jimoreira** [comment]
this is the geojson file
`{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-58.33143711090087,-33.35175265255656],[-58.331565856933594,-33.35189604309437],[-58.33006381988525,-33.35949540359959],[-58.32075119018555,-33.36365326339804],[-58.31336975097657,-33.36057073121353],[-58.31409931182861,-33.346016837375714],[-58.31585884094238,-33.33816532778627],[-58.31873416900635,-33.3377709410542],[-58.322768211364746,-33.34723572971968],[-58.33143711090087,-33.35175265255656]]]}}]}`

**Comment by jimoreira** [comment]
solved. 
for some reason, the API_KEY changed since the last time I have used. 
that was the issue, sorry for the troubles.
thanks again.

**Comment by samapriya** [comment]
HI @jimoreira I was able to use your geometry to get ids and create an order am glad you were able to solve it as well :)

**Comment by ShashankBice** [comment]
Hi Sam, I got into something similar, I did not receive a URL link but I can see the order at the endpoint you mentioned earlier. Any leads on how to go ahead ?
