### ISSUE TITLE
Error placing planet order

### ISSUE THREAD

**Issue by cmehofer76** [samapriya/porder#21]
Hello Samapriya,

Thanks for your work on porder.
Unfortunately i have a problem by placing an order:
**porder order --name "NOE_GAP_Clip" --idlist "C:\Users\MyName\planetGeo\orderlist.txt" --item "PSScene4Band" --asset "analytic" --boundary "C:\Users\MyName\planetGeo\ID5_NOE.geojson" --op clip zip email** doesn't work.

The error message i get:
{"field":{"Products":[{"message":"Item ID or Item Type empty"}]},"general":[{"message":"Unable to accept order"}]}

Can you please help me, to solve this issue. I read somewhere in the planet forum, that there was an issue with the Clip functionality in an older version of porder. I use porder v0.1.9

Thanks in advance
Christian

**Comment by samapriya** [comment]
Hi @cmehofer76 
There is no way for me to look at the issue without the idlist file and the GeoJSON file, so feel free to share them (Just click and drag to the reply window and they will get attached). This might be a case where your idlist file maybe empty.

**Comment by cmehofer76** [comment]
Hello Samapriya,
thanks for your reply. Fortunately i found a solution by myself, but i think i was lucky. I changed the
NUMBER parameter (creating idlist) from 800 (read that value in your tutorial) to 50 and voila,
everything worked fine.
Nevertheless i have another question: Is it possible to manually edit the orderlist.txt with a simple text
editor, e.g. if i already have a list of image-id's? Or if i want to delete a certain image-id from the list?
What is the purpose of the CSV file? What exactly is the "relation" between the TXT and the CSV?

Thanks
Christian

**Comment by samapriya** [comment]
Hi @cmehofer76 
yes, you can definitely edit and place the ids in the idlist file manually. The ids are initially written to a CSV file and the --number flag is used to choose and write only up to the maximum number of ids requested to the CSV and text file to make edits in place. I might decide to consolidate if needed in the future and get rid of the text file all together in a future release. I could not recreate the issue you had with 800 vs 50. If 800 assets do not exist, it should write to the maximum possible found and exit. I am closing this issue and will revisit it before next release.

**Comment by samapriya** [comment]
No more txt exports in release 0.2.1 onwards. Just created the release

**Comment by cmehofer76** [comment]
Hello,
thank you for your clarification. Keep up the good work!

Kind Regards
Christian
