### ISSUE TITLE
EPSG Code to be accepted by user, this is not available in skysat json ?

### ISSUE THREAD

**Issue by ShashankBice** [samapriya/porder#22]
Hi Samapriya,
The Skysat json does not contain the `epsg code` in it, I see that you use it to do the overlap calculation in `m units`. This can be overcomed in 2 ways, accept a epsg code from the user as an optional argument in idlist etc, or calculate a `local equal area coordinate` system from the input user geometry the tool takes in and then define everything with respect to that. These operations can be performed if the `['item']['properties']['epsg_code'] is None` or something. 
Thanks for putting up this tool.
Shashank

**Comment by samapriya** [comment]
Thanks @ShashankBice 
Will work this into the next few releases, I think letting a user pass this might be an easy way out.

**Comment by samapriya** [comment]
This issue is now resolved in v0.2.6, Skysat area is calculated using EPSG:3857 to resolve metadata EPSG issue.
