### ISSUE TITLE
order download link

### ISSUE THREAD

**Issue by AmeenAli** [samapriya/porder#33]
Wouldn't it be nice if we can also get the order download link by passing the order name other than only getting it via the email?

**Comment by samapriya** [comment]
Hi @AmeenAli 
I am not really sure I understand the ask here, the download tool here only requires your order URL, this is generated when you place the order and this is the only link you require to download your entire order. 

for example:

```
porder download --url "order URL" --local "full path to the folder where you want to download"
```

Closing this issue considering this resolves or points to the answer and/or there is nothing additional to solve here. However, if you mean something else, please add to the issue and we can continue the conversation
