### ISSUE TITLE
pyperclip doesn't work on systems without GUIs

### ISSUE THREAD

**Issue by rbavery** [samapriya/porder#4]
Hey Sam, thanks for the great tool! I'm trying to use porder from an aws instance, since eventually I'd like to use porder and computationally demanding tools in a single process on a infrastructure that can scale up. When I use `porder order` like so 

```
porder order --name test-aoi1-month07 --idlist ~/planet/cloud-free-planet/notebooks/test_aoi1_id.txt --item PSScene4Band --asset analytic_sr --boundary test_tile.geojson --aws ~/planet/cloud-free-planet/notebooks/aws.yaml --op aws

```

I get the following error, even though I've installed xsel and xclip. It sounds like it relates to this issue: https://stackoverflow.com/questions/51662213/cant-get-pyperclip-to-use-copy-and-paste-modules-on-python3

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/porder_env/bin/porder", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/porder_env/lib/python2.7/site-packages/porder/porder.py", line 204, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/porder_env/lib/python2.7/site-packages/porder/porder.py", line 96, in order_from_parser
    gcs=args.gcs)
  File "/home/ubuntu/anaconda3/envs/porder_env/lib/python2.7/site-packages/porder/order_now.py", line 171, in order
    clipboard.copy(str(url) + '/' + str(content['id']))
  File "/home/ubuntu/anaconda3/envs/porder_env/lib/python2.7/site-packages/pyperclip/__init__.py", line 616, in lazy_load_stub_copy
    return copy(text)
  File "/home/ubuntu/anaconda3/envs/porder_env/lib/python2.7/site-packages/pyperclip/__init__.py", line 301, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error 

```

This makes sense since the tool was developed for a personal machine environment. I can edit my own installation of porder to remove the use of clipboard, but thought I'd bring this up.

**Comment by samapriya** [comment]
Hi @rbavery seems it should be cross platform and should work in headless

https://github.com/asweigart/pyperclip

From the project website
```
On Mac, this module makes use of the pbcopy and pbpaste commands, 
which should come with the os.

On Linux, this module makes use of the xclip or xsel commands,
which should come with the os. Otherwise run "sudo apt-get install xclip"
or "sudo apt-get install xsel" (Note: xsel does not always seem to work.)
```

The simple fix, for now, would be to create a try except where if the copy fails the link is just printed if copy fails. I have used porder in linux before without issues in a headless Digital Ocean VM. Will work on this over the next couple of days. Let me know if installing those additional libraries worked instead.

**Comment by samapriya** [comment]
@rbavery the fix is now in place, the terminal simply prints the order incase of a headless setup without access to clipboard. Update to v0.1.3

**Comment by rbavery** [comment]
Awesome, thanks Sam.
