### ISSUE TITLE
porder order returns invalid geometry, also fails without geometry clipping for aws s3

### ISSUE THREAD

**Issue by rbavery** [samapriya/porder#5]
I'm trying the following with the given idlist and geojson (see attached)

```
porder order --name test-aoi1-month07 --idlist ~/planet/cloud-free-planet/notebooks/test_aoi1_id.txt --item PSScene4Band --asset analytic_sr --boundary test_tile.geojson --aws ~/planet/cloud-free-planet/notebooks/aws.yaml --op aws clip email
```

But the order status fails (from the email notification)

```
Name: test-aoi1-month07 
ID: 1a7252c6-6037-40e8-a3ca-1e274607157a 
Status: failed 
Duration: 2m35.768276919s

```

and also states that the geometry is invalid. The geojson is below

```
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "id": 0 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -0.831, 5.756599999999446 ], [ -0.7986, 5.756599999999446 ], [ -0.7986, 5.71 ], [ -0.831, 5.71 ], [ -0.831, 5.756599999999446 ] ] ] } }
]
}

```

[test_aoi1_id.txt](https://github.com/samapriya/porder/files/2808942/test_aoi1_id.txt)

The order also fails when I run the following command (no clipping). There's no error output so it's hard to diagnose

```
porder order --name test-aoi1-month07 --idlist ~/planet/cloud-free-planet/notebooks/test_aoi1_id.txt --item PSScene4Band --asset analytic_sr --boundary test_tile.geojson --aws ~/planet/cloud-free-planet/notebooks/aws.yaml --op aws clip email
```
I appreciate the help, let me know if there's any other info I can provide.

**Comment by samapriya** [comment]
Hi @rbavery paster the ordersv2 URL in your browser and log in with your planet credentials, and it should give you a readout of your errors much better. Since there is no way to ascertain what kind of error you are getting I would ask that you check that first and report back.

**Comment by kefuhai** [comment]
+1

Hey Sam, I'm seeing issues very similar @rbavery has shown. My command line output is below, with differences being idlist is a csv vs a text file (shouldn't matter), I'm not using AWS, and I don't receive any email output indicating the order never goes through in the first place.

I've also attached my idlist file and geojson file. Let me know if I can add more input; if you are looking for the ordersv2 URL would you be able to specify more what you are looking for?

-Kevin Kha

```
kxk8298@collins:~ $ porder order --name "LNL_1501_1_2018" --idlist "/dirs/home/ugrad/kxk8298/SeniorProjectData/TestImagery/LNL_505/link_file_100.csv" --item "PSScene4Band" --asset "analytic_sr" --boundary "/cis/ugrad/kxk8298/test/Lawnel_505.geojson" --op clip email
{"field":null,"general":[{"message":"Unable to accept order: geojson: invalid geometry"}]}
```

`{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -77.89538383483887,
              42.86445248146814
            ],
            [
              -77.88431167602539,
              42.86445248146814
            ],
            [
              -77.88431167602539,
              42.87165535908756
            ],
            [
              -77.89538383483887,
              42.87165535908756
            ],
            [
              -77.89538383483887,
              42.86445248146814
            ]
          ]
        ]
      }
    }
  ]
}`

`20181025_150419_0f49
20181021_153439_0f3f
20181020_153504_0f28
20181020_150441_0f1a
20181017_153413_1009
20181014_153428_1015
20181012_150633_0f3c
20181010_153438_1012
20181009_150628_0f1a
20181006_153433_1042
20181005_153304_102c
20180928_150730_0f1a
20180927_150843_1050
20180924_150907_104a
20180924_153312_1004
20180923_153301_1015
20180921_150923_1049
20180921_153319_0f42
20180919_153315_1012
20180918_150942_104d
20180916_153322_103c
20180915_151002_0f47
20180914_150927_101c
20180907_153304_1006
20180907_153305_1006
20180904_151159_0f46
20180904_153240_1033
20180901_151149_0f40
20180901_153155_1003
20180829_153209_101e
20180828_153238_102c
20180826_153313_0f43
20180826_153401_103b
20180825_153223_1038
20180824_151314_0f4d
20180819_151431_104a
20180818_152841_0e26
20180817_153153_1004
20180816_151420_1049
20180816_153151_1015
20180815_151522_0f44
20180815_153229_101f
20180815_153228_101f
20180812_151541_0f36
20180811_151517_1052
20180809_151445_1043
20180809_153156_101b
20180806_151432_103f
20180806_153207_0f3f
20180729_151629_0f1a
20180729_153130_0f35
20180728_151735_1050
20180727_153307_0f34
20180727_153136_0f25
20180726_151713_101c
20180723_153105_103c
20180722_153122_1042
20180721_153122_1002
20180720_153037_1032
20180719_153123_0f17
20180719_151856_104e
20180718_153115_1044
20180717_151908_1053
20180717_153100_1024
20180716_153025_1018
20180714_153103_1013
20180713_152003_0f3d
20180711_152937_0e2f
20180710_153122_0f25
20180709_153026_100a
20180708_152020_1049
20180708_153105_100e
20180707_153010_1014
20180707_153118_1035
20180706_153042_103c
20180705_153106_1042
20180704_152139_0f36
20180704_153038_1002
20180703_153136_0f3f
20180703_153002_1032
20180702_152123_0f46
20180701_153047_1044
20180630_152126_0f2a
20180630_153022_1024
20180629_153050_1009
20180626_152239_1054
20180625_153018_0f35
20180622_152924_100a
20180621_152958_100e
20180621_152226_104d
20180619_153036_101b
20180618_152350_0f46
20180618_153005_1042
20180617_152908_1002
20180616_152314_0f2a
20180616_153016_0f3f
20180615_152303_0f40
20180615_153035_0f28
20180614_153050_102e
20180612_152914_1009`

**Comment by kefuhai** [comment]
Playing around with things a bit more, it looks like I'm able to enter anything for the boundary arguement to replicate this error, regardless if the provided string is a file or not. Going further not including the tag results in the same error.

`porder order --name "LNL_1501_1_2018" --idlist /dirs/home/ugrad/kxk8298/SeniorProjectData/TestImagery/LNL_505/link_file_100.csv --item "PSScene4Band" --asset "analytic_sr" --boundary jibberish --op clip email{"field":null,"general":[{"message":"Unable to accept order: geojson: invalid geometry"}]}`

```
porder order --name "LNL_1501_1_2018" --idlist /dirs/home/ugrad/kxk8298/SeniorProjectData/TestImagery/LNL_505/link_file_100.csv --item "PSScene4Band" --asset "analytic_sr" --op clip email
{"field":null,"general":[{"message":"Unable to accept order: geojson: invalid geometry"}]}
```

**Comment by samapriya** [comment]
Hi @kefuhai and @rbavery 
Here is what I would recommend
* Go to https://api.planet.com/compute/ops/orders/v2
* Put your API key as username and hit enter/return
* Check the order you placed, and actually check the error, I think the returned error from server may not be the actual reason it failed but rather things like an insufficient quota or incorrect aws credentials and so on.

I just placed an order with your geojson file (Lawnel_1501) and it just completed . Also @kefuhai passing gibberish as boundary will fail for obvious reasons :)

Hope that helps, I suspect the message being passed back from the server is not giving you enough reason for the failure.

**Comment by kefuhai** [comment]
@samapriya Thank you for the response, I'll take a closer look. I threw in 'jibberish' just to illustrate that regardless of what I input as the boundary file that the file wasn't being read in. Through further experimentation I ended up downloaded the repository over and doing a call of 'python3 porder.py order ...' and that worked, so something with the module installation such that it can be called by 'porder order ...' is bugged on my end.

Just for clarity, are all error messages for porder handled by server side, not local side?

Again, thanks for your patience!

**Comment by samapriya** [comment]
Thanks for reporting back @kefuhai . All messages are generated server side, because if the POST request to create the order does not return a 202 then the program simply reads out what is returned. I usually end up checking with the order url in my browser sometimes to look for errors. At this point since this is no longer an issue with the program and rather an order authentication or quota issue, I am closing this for now.

**Comment by rbavery** [comment]
Hi Sam, reopening this after trying to order while clipping again

When I run this

```
(v2-cloud)~/cloud-free-planet/notebooks$ porder order --name test-tile_fourth --idlist ~/cloud-free-planet/notebooks/test_fourth_ids.txt --item PSScene4Band --asset analytic_sr --boundary test_tile_fourth.geojson --op clip email
Could not parse geometry
{"field":null,"general":[{"message":"Unable to accept order: geojson: invalid geometry"}]}

```

There's no order url that is printed so I can't check the error message as you suggested. I tried to run without clipping:

```
(v2-cloud)~/cloud-free-planet/notebooks$ porder order --name test-tile_fourth --idlist ~/cloud-free-planet/notebooks/test_fourth_ids.txt --item PSScene4Band --asset analytic_sr --boundary test_tile_fourth.geojson
Order created at https://api.planet.com/compute/ops/orders/v2/268eb482-0622-4373-aaf6-4f75fea64c61 and url copied to clipboard
```

But I get this error when I check the url

```
{
"_links": {
"_self": "https://api.planet.com/compute/ops/orders/v2/268eb482-0622-4373-aaf6-4f75fea64c61"
},
"created_on": "2019-02-19T22:19:26.462Z",
"error_hints": [
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)"
],
"id": "268eb482-0622-4373-aaf6-4f75fea64c61",
"last_message": "Order resulted in 0 assets",
"last_modified": "2019-02-19T22:20:23.603Z",
"name": "test-tile_fourth",
"order_type": "partial",
"products": [
{
"item_ids": [
"20180703_095732_1015",
"20180610_095739_1008",
"20180606_104025_0f3c",
"20180602_095704_1018",
"20180602_104029_1053",
"20180601_104054_0f46"
],
"item_type": "PSScene4Band",
"product_bundle": "analytic_sr"
}
],
"state": "failed",
"tools": [
{
"bandmath": {}
}
]
}
```

I thought this might be because I included the `--boundary` option without specifying `--op clip` (not sure if these are dependent on each other. But when I run this without the boundary option or clipping

```
(v2-cloud)~/cloud-free-planet/notebooks$ porder order --name test-tile_fourth --idlist ~/cloud-free-planet/notebooks/test_fourth_ids.txt --item PSScene4Band --asset analytic_sr
Order created at https://api.planet.com/compute/ops/orders/v2/672a85c9-585e-4c65-af4c-6f2767eddbcb and url copied to clipboard

```

I get the same error as above

```
{
"_links": {
"_self": "https://api.planet.com/compute/ops/orders/v2/672a85c9-585e-4c65-af4c-6f2767eddbcb"
},
"created_on": "2019-02-19T22:20:55.481Z",
"error_hints": [
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)",
"There are no result bands produced, operation fails. (code: FAILURE_CODE_INVALID_INPUT Bandmath_v1)"
],
"id": "672a85c9-585e-4c65-af4c-6f2767eddbcb",
"last_message": "Waiting for per-bundle operations to complete. Running 0, Succeeded 0, Failed: 6",
"last_modified": "2019-02-19T22:21:47.901Z",
"name": "test-tile_fourth",
"order_type": "partial",
"products": [
{
"item_ids": [
"20180703_095732_1015",
"20180610_095739_1008",
"20180606_104025_0f3c",
"20180602_095704_1018",
"20180602_104029_1053",
"20180601_(v2-cloud)~/cloud-free-planet/notebooks$ porder order --name test-tile_fourth --idlist ~/cloud-free-planet/notebooks/test_fourth_ids.txt --item PSScene4Band --asset analytic_sr
Order created at https://api.planet.com/compute/ops/orders/v2/672a85c9-585e-4c65-af4c-6f2767eddbcb and url copied to clipboard
104054_0f46"
],
"item_type": "PSScene4Band",
"product_bundle": "analytic_sr"
}
],
"state": "running",
"tools": [
{
"bandmath": {}
}
]
}
```

Here is my geojson

```
{
"type": "FeatureCollection",
"name": "test_tile_fourth",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 0 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -0.831053947078279, 5.733240915104465 ], [ -0.815377541344895, 5.733079073869626 ], [ -0.815323594266615, 5.709838158765161 ], [ -0.831, 5.71 ], [ -0.831053947078279, 5.733240915104465 ] ] ] } }
]
}
```

I'm not sure what to make of the error, especially since the idlist was created successfully. Here's what I used to create the idlist

```
(v2-cloud)~/cloud-free-planet/notebooks$ porder idlist --input "/home/rave/cloud-free-planet/notebooks/test_tile_fourth.geojson" --start "2018-06-01" --end "2018-08-31" --item "PSScene4Band" --asset "analytic_sr" --number 10000 --outfile "/home/rave/cloud-free-planet/notebooks/test_fourth_ids.csv" --cmin 0 --cmax .5 --overlap 100
```

Any help or suggestions are appreciated, thank you! Let me know if I can provide more info.
