### ISSUE TITLE
Python 3.X invalid syntax for print statement in multiproc_pydl.py line 99

### ISSUE THREAD

**Issue by prod29** [samapriya/porder#6]
Using Python 3.6.6
Received the following error when trying to use the multiproc tool:
```
  File "multiproc_pydl.py", line 99
    print msg, multiprocessing.current_process().name
            ^
SyntaxError: invalid syntax
```

Fixed it by simply adding a () around the print statement to follow Python 3.X print syntax.

`print (msg, multiprocessing.current_process().name)`

Other than that... love the porder CLI tool!!! Keep up the good work!

**Comment by samapriya** [comment]
Thanks for reporting, just fixed this in 0.1.6
